version: '3'
services:
  postgres-db:
    image: postgres:9.6
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: instagram
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:
