version: '3'
services:
  postgres-db:
    image: postgres:9.6
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: instagram
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  mailhog:
    image: mailhog/mailhog:latest
    platform: linux/amd64
    restart: always
    ports:
      - 1025:1025
      - 8025:8025
volumes:
  postgres-data:
