version: '3'
services:
  web:
    build: .
    ports:
      - "8000:8000"
    networks:
      - instagram-backend
    depends_on:
      - postgres-db
    env_file:
      - .env
    environment:
      - SMTP_HOST=mailhog
      - DATABASE_URL=postgresql://postgres:postgres@postgres-db:5432/instagram?schema=public
  postgres-db:
    image: postgres:9.6
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: instagram
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - instagram-backend
  mailhog:
    image: mailhog/mailhog:latest
    platform: linux/amd64
    restart: always
    ports:
      - 1025:1025
      - 8025:8025
    networks:
      - instagram-backend
volumes:
  postgres-data:
networks:
  instagram-backend:
